---
options:
  formatter: html
  merge-default-rules: false
  output-file: linters/sass-lint.html
rules:
  border-zero:
  - 1
  - convention: none
  clean-import-paths:
  - 1
  - filename-extension: true
  declarations-before-nesting: 2
  empty-args:
  - 1
  - include: true
  empty-line-between-blocks:
  - 2
  - allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  function-name-format: 2
  hex-length:
  - 1
  - style: long
  hex-notation: 2
  indentation:
  - 2
  - size: 4
  leading-zero:
  - 2
  - include: true
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format: 2
  mixins-before-declarations: 2
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  property-sort-order:
  - 2
  - order: concentric
  property-units: 0
  pseudo-element: 2
  quotes: 2
  shorthand-values: 0
  single-line-per-selector: 0
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 0
  space-before-brace: 2
  space-before-colon: 0
  space-between-parens: 0
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 2
  zero-unit:
  - 2
  - include: true
